title="FTM_USDT_BINANCE"

[general]
pair="FTM USDT"
exchange="Binance"
strategy="DCA"

[parameters]
cycle="onetime"
first_buy_in=11
take_profit_ratio=1.1
margin_call_limit=5
earning_callback=0.5
sub_position_start=5

[margin]
margin_configuration=[
	[2.5, 1.0],
	[3.5, 3.0],
	[1.5, 1.0],
	[4.5, 3.0]
]
sub_position_profit_ratio = [ 1.2, 2.1, 1.3, 4.5 ]
sub_position_earning_callback = 0.2

