kind = "bot"
title = "ARB_USDC_BINANCE"

[general]
pair = "ARBUSDC"
platform = "binance"
strategy = "martingle"

[parameters]
cycle = "repeat"
first_buy_in = 10
take_profit_ratio = 1.5
earning_callback = -0.2

[margin]
margin_configuration = [[-1, 2], [-2, 3], [-2, 3]]
