kind = "bot"
title = "SUI_USDC_BINANCE"

[general]
pair = "SUIUSDC"
platform = "binance"
strategy = "helldiver"

[parameters]
cycle = "repeat"
first_buy_in = 10
take_profit_ratio = 1.9
earning_callback = -0.3

[margin]
margin_configuration = [[-1, 0.5, 2], [-4, 0.5, 6]]
