kind = "bot"
title = "ENAUSDT"
pair = "ENAUSDT"
base = "ENA"
quote = "USDT"
platform = "binance"
strategy = "helldiver"
status = "PAUSED"

[parameters]
cycle = "repeat"
first_buy_in = 10.0

[parameters.entry]
mfi_below = 25.0
mfi_callback = 10.0
price_change_below = -2.0
price_callback = 1.0
amount_ratio = 1

[parameters.take_profit]
price_change_above = 2.0
price_callback = -0.3

[[margin.margin_configuration]]
mfi_below = 25.0
mfi_callback = 10.0
price_change_below = -2.0
price_callback = 1.0
amount_ratio = 4

[[margin.margin_configuration]]
mfi_below = 25.0
mfi_callback = 10.0
price_change_below = -7.0
price_callback = 1.0
amount_ratio = 15
