kind = "bot"
title = "PENGUUSDT"

[general]
pair = "PENGUUSDT"
base = "PENGU"
quote = "USDT"
platform = "binance"
strategy = "helldiver"

[parameters]
cycle = "repeat"
first_buy_in = 5
take_profit_ratio = 2.0
earning_callback = -0.3

[margin]
margin_configuration = [[-1.5, 0.5, 4.0], [-6, 1.0, 15.0]]
